### ISSUE TITLE
With material-ui, cell style is not working as expected

### ISSUE THREAD

**Issue by codingdash** [adazzle/react-data-grid#1541]
### Which version of React JS are you using?
- v16.x.x

---

### Which browser are you using?
- Chrome
- Firefox
- Safari

---

### I'm submitting a ...
- Bug Report

### Issue Details

When used `react-data-grid` with `@material-ui/core@3.7.0` facing style issue with the columns. The column configration is set as below:

```javascript
const columns = [
  {
    key: 'id',
    name: 'Id',
    width: 120,
    resizable: true,
    frozen: true
  },
  {
    key: 'status',
    name: 'Status',
    width: 120,
    resizable: true
  },
  {
    key: 'created_at',
    name: 'Created At',
    width: 120,
    resizable: true
  }
];
```

And the view looks something like below:

<img width="500" alt="Screenshot 2019-03-29 at 4 13 14 PM" src="https://user-images.githubusercontent.com/8619844/55227526-ba160a00-523d-11e9-834d-6b4e0e43e701.png">

After inspecting the elements, it looks like when [generating style](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/HeaderCell.js#L78) for each cell, the `left` style value doesn't consider adding `width` of [ResizeHandle component](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/HeaderCell.js#L125).

**Comment by codingdash** [comment]
Adding below CSS has solved the problem!

```css
* {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
*:before,
*:after {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```
