### ISSUE TITLE
Horizontal scrolling a selected row with locked column(s) shows the non-locked column data behind locked columns 

### ISSUE THREAD

**Issue by gareth-smyth** [adazzle/react-data-grid#241]
Hi all,

**Scenario**
- Grid with single locked column and other non-locked columns.
- Width of the combined columns allows horizontal scrolling on the table.
- Row(s) selected.

**Problem**
When the non-locked columns are scrolled the values in the selected row(s) appear visible "underneath" the locked column(and the select checkbox cell).

**Replication**
I'm not sure how to get an example working for react-data-grid in jsfiddle but this can be replicated in the example at http://adazzle.github.io/react-data-grid/examples.html#/single-row-select by 
- setting the first column to fixed: true
- setting a column width on each of the columns to some suitably high value to show the horizontal scrollbar 
- selecting a row and scrolling left and right.

**Example**
![selected_locked_column](https://cloud.githubusercontent.com/assets/6697040/13550773/f2588412-e31c-11e5-8ae8-675b80e7ceb7.gif)

**Cause/Solution**
When a row is selected the following css creates an almost transparent background-color on the row

``` css
.react-grid-Row.row-selected .react-grid-Cell{
 background-color: rgba(16, 126, 219, 0.15);
}
```

The rest of the grid has no aplha channel applied so I'd suggest  changing this to

``` css
.react-grid-Row.row-selected .react-grid-Cell{
 background-color: rgb(219, 236, 250);
}
```

which gives the same visible colour. Let me know what you think - i've made this change in https://github.com/gareth-smyth/react-data-grid.  I've only been using the grid for a day so I've no idea if this is likely to break anything else.
