### ISSUE TITLE
Passing a class to prevent text overflow does not work as expected.

### ISSUE THREAD

**Issue by danfernand** [adazzle/react-data-grid#245]
If I try to pass a column definition to prevent text overflow like such
```javascript
const columns = [
...
  {
    key: 'problem',
    name: 'Problem',
    cellClass: 'no-overflow',
  }
...
];
```
the class is defined like so
```
.no-overflow {
  text-overflow: ellipsis;
}
```

The cell does not prevent text from overflowing to the next line

**Comment by danfernand** [comment]
Was able to, solve with some css, basically you need to target the div that owns the text
```
.no-overflow .react-grid-Cell__value div {
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
}
```
It's a lil odd and maybe can be a built in to the column properties, but that would be an enhancement

**Comment by siliconeidolon** [comment]
Thanks for posting your solution to this, Dan - helped me.

**Comment by joinsunil** [comment]
@danfernand But it is not working for custom components in table cell. Please suggest some workaround..

**Comment by wesleyramalho** [comment]
I was able to enable text wrapping with a CSS workaround:

this is the result:
![image](https://user-images.githubusercontent.com/21203415/151071344-7a0c8ff6-5ee1-4e45-82b6-2365ff71482a.png)


to achieve this, I just:
- added the property ```cellClass: css.myClassThatEnablesTextWrapping``` to each item of the columns
- and this is the content of the CSS class:
```css
.myClassThatEnablesTextWrapping {
  text-overflow: ellipsis;
  white-space: break-spaces;
  overflow-y: auto;
 // this is another workaround that makes the scroll appears only for cases where it is really necessary
  height: calc(100% + 2%);
}
```

This solution works for:
- ✅ editable cells 
- ✅ resizable cells
