### ISSUE TITLE
Easiest way to enable text wrapping?

### ISSUE THREAD

**Issue by alvaro1728** [adazzle/react-data-grid#248]
Hi and once again, thanks for this great component!  

I have a row with a "description" column that truncates its text when it overflows.  What's the easiest way to allow the row height to expand to accommodate text wrapping?

Thanks,
Alvaro

**Comment by danfernand** [comment]
I literally had to figure this out with the help of the contributors.

https://github.com/adazzle/react-data-grid/issues/245

**Comment by jpdriver** [comment]
hey @alvaro1728 -- see @danfernand 's linked issue above if you want to include an ellipses for the text overflow.

if you wanted something more like dynamic height which automatically expands a row, we don't have anything like that currently... You could pass in a custom `rowHeight` to the grid, but at the moment this will apply to all rows.

do either of those options suit your use case?

**Comment by alvaro1728** [comment]
Hi @danfernand and @jpdriver, thanks for your replies.

I guess I was looking more for the typical HTML table behavior where if a td has too much text, it automatically wraps it and makes that row taller.  However... I came up with a slicker solution, or so I think. :-)  I'm wrote some jquery/css code that attaches a mouseenter event to my "description" cells to dynamically expand their height and show the full text.  

![image](https://cloud.githubusercontent.com/assets/4854341/13766995/d56a98b4-ea23-11e5-8f22-2f5c0ab67f51.png)

![image](https://cloud.githubusercontent.com/assets/4854341/13767001/de54a032-ea23-11e5-9df4-0adbfd9bd30c.png)

Let me know if you're interested in my concoction.

Thanks,
Alvaro

**Comment by jpdriver** [comment]
nice! any chance you could open a PR for it? think we'd definitely be interested to see :smile:

**Comment by diogofcunha** [comment]
Will close as it is a duplicated for #102

**Comment by strygul** [comment]
@alvaro1728 How did you calculate the height that you need to expand the row?

**Comment by joinsunil** [comment]
Any update on this feature ?

**Comment by rao123dk** [comment]
This library releasing new version on every month like angular, but still not solved dynamic row height related issue which is most used in data table. After spending 2 month in my project, and this issue forcing me to adopting another table library.

**Comment by sheshagiri-t** [comment]
@rao123dk Can you please share the library that you used to achieve dynamic row height?

**Comment by rao123dk** [comment]
> @rao123dk Can you please share the library that you used to achieve dynamic row height?

https://github.com/DevExpress/devextreme-reactive .

**Comment by wesleyramalho** [comment]
I was able to enable text wrapping with a CSS workaround:

this is the result:
![image](https://user-images.githubusercontent.com/21203415/151071344-7a0c8ff6-5ee1-4e45-82b6-2365ff71482a.png)


to achieve this, I just:
- added the property ```cellClass: css.myClassThatEnablesTextWrapping``` to each item of the columns
- and this is the content of the CSS class:
```css
.myClassThatEnablesTextWrapping {
  text-overflow: ellipsis;
  white-space: break-spaces;
  overflow-y: auto;
 // this is another workaround that makes the scroll appears only for cases where it is really necessary
  height: calc(100% + 2%);
}
```

**Comment by ianmaciel7** [comment]
```css
.test {
    display: inline-block;
    line-height: 1.5;
    overflow-wrap: break-word;
    white-space: normal;
    text-align: justify;
}
```
